# Generated by Django 5.1.3 on 2024-12-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Task', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
